### ISSUE TITLE
global Docker and readme 

### ISSUE THREAD

**Issue by aremazeilles** [jamatics/pi_ctag#1]
It seems that you are preparing a docker image per routines.
The interest of Docker is to secure the code installation and reduce risks of library conflicts.
Then, I would rather go for a docker image containing all your different entry points to compute the PI, and bringing at the root of your package all run_pi scripts.
That would be a docker for the whole respository

I could help you with that, if you indicate me the list of entry points for running your different PI code. This might even be better to identify before, for each program you intend to use which are:

* the script to launch
* how to call it
* example of input file
* generated output file given these input file (for testing)

**Comment by jamatics** [comment]
I will appreciate your @aremazeilles support.
I have included the information at 
[dockerCTAG.xlsx](https://github.com/jamatics/pi_ctag/files/4817187/dockerCTAG.xlsx)
I will be happy to provide more details.

**Comment by aremazeilles** [comment]
Would you mind putting me as contributor to the repository? It could make the collabortion slightly easier.

**Comment by jamatics** [comment]
I have added you as a collaborator.

**Comment by aremazeilles** [comment]
I think this issue can be closed, as more specific ones get created
