### ISSUE TITLE
[input] missing csv header

### ISSUE THREAD

**Issue by aremazeilles** [jamatics/pi_ctag#10]
Looking at the input- output format

File [balance.csv](https://github.com/jamatics/pi_ctag/blob/master/testdata/input/balance.csv) is missing an header row.

**Comment by jamatics** [comment]
Hi Anthony, This is a dummy data file created for testing the balance PI. This PI is dependent on the CSIC facilities force plates. We can structure the input data columns for using two force plates, one for left and second for right (time_stamp, left_force_x, left_force_y, left_force_z, left_moment_x, left_momenty, left_moment_z, similarly next six columns for right side force plate). Please confirm, what you prefer and I will change the input file. You may already have some format defined for the force plate/ground reaction force measurement. 
Thanks,
Jawad

**Comment by aremazeilles** [comment]
We have suggested a format for the [wrench file](https://eurobench.github.io/sofware_documentation/latest/data_format.html#_wrench_file).

In the case that you want to put the two set of mesurement in the same file, we suggest in [that section](https://eurobench.github.io/sofware_documentation/latest/data_format.html#_protocol_with_multiple_but_similar_sensors) that the label could be indeed started with a tag like "left_" and " right_" (as proposed in the second table of that section)

**Comment by jamatics** [comment]
I have pushed the changes. Please check.

Thanks, 
Jawad

**Comment by aremazeilles** [comment]
OK. It would have been great to name the file according to the content (like `wrench_balance.csv`, but I think this is for now a minor issue.
