### ISSUE TITLE
[input] more explicit column name

### ISSUE THREAD

**Issue by aremazeilles** [jamatics/pi_ctag#11]
in File [chrono.csv](https://github.com/jamatics/pi_ctag/blob/master/testdata/input/chrono.csv), I would suggest to put a more explicit label than `sensor_{1,2,3}`. What is the sensor measure?

Globally speaking, we have the policy to get all data format defined in the [documentation](https://github.com/aremazeilles/eurobench_documentation/blob/master/data_format.adoc).
We accept special files like  [platformData.csv](https://github.com/aremazeilles/eurobench_documentation/blob/master/data_format.adoc#testbed-platform-specific-data-recorded) for data being of several format. We can also envision having several ones if needed.

**Comment by jamatics** [comment]
I have pushed the changes. Please check. Now the file is the same as generated by the Node-Red.  

Thanks, 
Jawad
