### ISSUE TITLE
[input] hrv format

### ISSUE THREAD

**Issue by aremazeilles** [jamatics/pi_ctag#12]
We are proposing a format for [physiological data](https://github.com/aremazeilles/eurobench_documentation/blob/master/data_format.adoc#611-physiological-data).
I assume this is related to you [hrv.csv](https://github.com/jamatics/pi_ctag/blob/master/testdata/input/hrv.csv) data.

As commented in the documentation, you can just place and fill the appropriate column, but we would require the timestamp, and the label of the data you have in that file, possibly using one of the format we propose, if any makes sense in your case.

**Comment by jamatics** [comment]
Hi Anthony, our measurement device doesn´t provide a timestamp. In addition, I cannot access the https://github.com/aremazeilles/eurobench_documentation/blob/master/data_format.adoc#611-physiological-data

Thanks, 
Jawad

**Comment by aremazeilles** [comment]
My apologies for the bad link, the file has moved since.
The Eurobench is defined in this [folder](https://github.com/aremazeilles/eurobench_documentation), which get rendered then [there](https://eurobench.github.io/sofware_documentation/latest/data_format.html#_physiological_data).
The last link points to the physiological format.

> our measurement device doesn´t provide a timestamp
That is where I would put the distinction in between the raw-data and the pre-processed data. The raw data would be the file as the measurement device provides it, i.e. without timestamp. The pre-processed data format would be that file follwoing the suggestion we do, i.e adding a time-stamp to the file. I assume that you would be setting somewhere an apriori on the timestamp in between each entry. It would be better to insert it into the file. If you would need some help in doing so, I can provide support.

**Comment by jamatics** [comment]
I have added the header and also change the milliseconds to seconds according to [EB_Documentation](https://eurobench.github.io/sofware_documentation/latest/data_format.html#_wrench_file).  

Thanks, 
Jawad

**Comment by aremazeilles** [comment]
It would have been great adding a column with the timestamp. 
I would keep it as a minor issue.
