### ISSUE TITLE
[input] configuration yaml file

### ISSUE THREAD

**Issue by aremazeilles** [jamatics/pi_ctag#13]
A good practice is to distinguish the specification associated to the subject participating to the experiment from the data related to the configuration of the testbed, or conditional settting.

In the two yaml  you have:

[testbed_lowAssist](https://github.com/jamatics/pi_ctag/blob/master/testdata/input/testbed_lowAssist.yaml)

if `subject_weight` is what it literally means, it could be placed in another specific file.

[testbed_loadAssist_metaboliccist.yaml](https://github.com/jamatics/pi_ctag/blob/master/testdata/input/testbed_lowAssist_metaboliccost.yaml)

I see `subject_weight`, `gender` that are also related to the subject information. 

We could assume all this information could be placed in a dedicated `subject_info.yaml` for isntance, and be common across the algorithms. The rest is related to the testbed configuration more or less?

It might be good there to look at a "complete" set of files that could correspond to an experiment, to see how all this configuration parameters could be handled? I know for sure you are handling them perfectly in your setup, but this is less obvious to me still for making the computation automatically on our side.

**Comment by jamatics** [comment]
I am thinking to shift the subject information to another .yaml file according to [EB_Documentation](https://eurobench.github.io/sofware_documentation/latest/data_format.html#_wrench_file). To update these changes and previous changes I must update the source code as well. I would like to keep this issue open until I will resolve it completely. 
Stay tuned. 
Jawad

**Comment by jamatics** [comment]
Hi Again, 

I have created new file for subject information called subject_01_info.yaml and stack all information for the testbed in condition.yaml file. Both files are pushed to master. With this, we can close this issue. 

Thanks, 
Jawad
