### ISSUE TITLE
PI algo

### ISSUE THREAD

**Issue by aremazeilles** [jamatics/pi_ctag#14]
I have been revising the excel sheet, protocol and PIs.

Looking at the Pi Algo. I think you have defined one per PI.
We can go with that.
We could also for something like for the [beat protocol](https://github.com/aremazeilles/beat_routine), which turns to be simpler: Like you they have a set of entry points for computing each of the metrics [each described here](https://github.com/aremazeilles/beat_routine#performance-indicator-launch). But to simplify, we provide another entry point that is per protocol, [here](https://github.com/aremazeilles/beat_routine#protocol-benchmark). This entry point then internally calls each of the pi routines associatd to it.

If in your case all PIs are valid for all metrics, we could imagine a unique entry point, like `run_pi_ctag`. Eventually we could distinguish the one related to questionnaire, as this one may not be repeated, while the other may have different runs.

Any opinion to that respect?

Maybe to help understanding if this makes sense or not, could you share a listing of files that would correspond  to an experiment to benchmark? I know you already provided some, I am not sure they are final.

**Comment by aremazeilles** [comment]
To complete the integration of the code, dploy it onto the server, and enable automatic computation on data collected, we need to adress this. To do so, I would need to see the list of files that you collect in an experiment (you  may have already shared some data, sorry to ask it again), to check if it follows the policy we suggested, and  if not, to see how we can mitigate this.

We can set a meeting to discuss this if needed.

**Comment by aremazeilles** [comment]
Hello @jamatics 


In the experimental files you shared with me some times ago, I see:

```
$ ls
condition_01.yaml
subject_01_cond_01_choice_metabolicCost.yaml
subject_01_cond_01_run_01_balance.csv
subject_01_cond_01_run_01_chrono.csv
subject_01_cond_01_run_01_hrv.csv
subject_01_cond_01_run_01_jointAngles.csv
subject_01_cond_01_run_03_questionnaire_borgScale10.csv
subject_01_cond_01_run_03_questionnaire_medAssist.csv
subject_01_info.yaml
```

The metabolic cost choice file is problematic, with the current numbering. To better see its scope could you indicate how would be named the files collected in an experiment with 2 subjects, 2 conditions and 2 run per condition? Just the file name as above would be sufficient.

**Comment by jamatics** [comment]
Sorry for the late reply as somehow I missed your message.
This file remains consistent throughout the run, i.e. *run independent*. It
depends only on the subject and the testing conditions. So for 2 subjects,
2 conditions, 2 runs, you can use four files only.
1. subject_01_cond_01_choice_metabolicCost.yaml
2. subject_01_cond_02_choice_metabolicCost.yaml
3. subject_02_cond_01_choice_metabolicCost.yaml
4. subject_02_cond_02_choice_metabolicCost.yaml

I would like to ask you another question. Is the Eurobench Software is
ready to be used for call2? We have another project tested2.0 where we need
to use EB software for two scenarios. Can you send me the details to check
the main requirements of all relevant PI´s for sit to stand and walking in
straight lines?

Thank you,

Jawad

**Comment by aremazeilles** [comment]
Thanks Jawad for your answer, We are checking how to handle this. 

With respect to the Eurobench software, we are uploading the algorithm as soon as they are compliant with the Eurobench system. The current state of all of them are indicated on there: https://github.com/eurobench/eurobench_protocol

Regarding sit to stand, we have the two protocols uploaded:

* http://15.237.22.1/protocols/info/57
* http://15.237.22.1/protocols/info/58

Then indeed, I can see there is no manual. I can check that with the protocol providers if you want.

I think straight walking is not yet implemented, I can also check it with CSIC for your convenience.

**Comment by aremazeilles** [comment]
After checking with my colleague, it seems we could handle it if we rename the file as subject_01_condition_01_choice_metabolicCost.yaml  (i.e writing `condition` instead of `cond`).
As it is a file created manually, I assume thsi name change is not a problem for you, and I propose to change your reference file and documentation accordingly. Would that be ok for you?

**Comment by aremazeilles** [comment]
Hello @jamatics 

So for bench, the protocol description is currently available at: https://github.com/eurobench/eurobench_protocol/tree/add_bench_doc/data/bench/manual 

Regarding the straight walking, CSIC told me than the same metrics as the "walking on irregular terrain" would be used.
The manual is there: https://github.com/eurobench/eurobench_protocol/tree/add_bench_doc/data/csic-irregular/manual

Both should be soon uploaded to the website.
