### ISSUE TITLE
run_pi_x

### ISSUE THREAD

**Issue by aremazeilles** [jamatics/pi_ctag#4]
add all run_pi_x in the root folder, like for the balance case

Do you think you can handle it?

**Comment by jamatics** [comment]
Yes sure. I can handle this issue.

**Comment by jamatics** [comment]
Added.

**Comment by aremazeilles** [comment]
A good practice is to create a branch, make the change in that branch, and then make a Pull request to mention that the issue has been addressed. I am going to do it, as I notices some aspects that would need to be addressed.
