### ISSUE TITLE
gather test data

### ISSUE THREAD

**Issue by aremazeilles** [jamatics/pi_ctag#6]
Right now we have all test data distributed along each pi:

* balance &rarr; subject_01_run_01_balance.csv subject_01_testbed_lowAssist.yaml
* borg scale &rarr; subject_01_questionnaire_borgScale10.csv
* chrono &rarr; subject_01_run_01_chrono.csv
* hrMonitoring &rarr;  subject_01_run_01_hrv.csv
* metabolic cost &rarr; subject_01_run_01_chrono.csv subject_01_testbed_lowAssist.yaml
* questionnaire &rarr; subject_01_questionnaire_medAssist.csv
* range of Motion &rarr; subject_03_run_01_jointAngles.csv

I would like to gather all input data files in an unique folder, as if it was the collection of data during an experiment (involving in that case a unique run, unique user, unique condition).

I had a look, and I saw that:

* subject_01_run_01_chrono.csv is similar in chrono and metabolic cost
* subject_01_testbed_lowAssist.yaml is different in between balance and metabolicCost
  * using yaml from metabaloc cost does not change the balance score (but metabolicCost cannot be computed with the yaml from balance)
* the other files are only used per a unique PI.

Am I correct?

Would you agree gathering them in an unique folder? If yes I would do so and simplify the file naming.

**Comment by jamatics** [comment]
1. Yes, you are correct. The subject_01_testbed_lowAssist.yaml file in metabolic cost input folder is richer in information so I would like to retain it. The subject_01_run_01_chrono.csv files are the same. 
2. Yes, I agree to gather them in a unique folder, if it simplifies and clarifies thing and follow EB standard. 

Jawad
